# Generated by Django 4.2.7 on 2023-11-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dia',
            name='dia',
            field=models.CharField(max_length=15),
        ),
    ]
