# Generated by Django 4.2.7 on 2023-11-10 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controler', '0003_dia_hora'),
    ]

    operations = [
    ]
