# Generated by Django 4.2.7 on 2023-11-10 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controler', '0004_auto_20231110_1046'),
    ]

    operations = [
    ]
