# Generated by Django 4.2.7 on 2023-11-10 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controler', '0007_auto_20231110_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='dia',
            name='hora',
            field=models.TimeField(default=datetime.time(10, 59, 31, 710058)),
        ),
    ]
