# Generated by Django 4.2.3 on 2023-11-14 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controler', '0008_pago_fecha_creacion_alter_dia_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dia',
            name='hora',
            field=models.TimeField(default=datetime.time(18, 25, 3, 525864)),
        ),
    ]
