# Generated by Django 4.2.3 on 2023-11-15 10:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0002_ejercicio_remove_rutina_imagen_rutina_ejercicios'),
        ('controler', '0009_alter_dia_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rutina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rutina.rutina'),
        ),
        migrations.AlterField(
            model_name='dia',
            name='hora',
            field=models.TimeField(default=datetime.time(7, 54, 44, 254228)),
        ),
    ]
