# Generated by Django 4.2.3 on 2023-11-16 14:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controler', '0011_alter_dia_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dia',
            name='hora',
            field=models.TimeField(default=datetime.time(11, 39, 20, 611881)),
        ),
        migrations.CreateModel(
            name='RegistroDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pagos', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_diarios', to='controler.dia')),
            ],
        ),
    ]
