# Generated by Django 4.2.3 on 2023-11-16 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controler', '0012_alter_dia_hora_registrodiario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dia',
            name='hora',
            field=models.TimeField(default=datetime.time(17, 16, 3, 641888)),
        ),
        migrations.DeleteModel(
            name='RegistroDiario',
        ),
    ]
