# Generated by Django 4.2.7 on 2023-11-30 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controler', '0013_alter_dia_hora_delete_registrodiario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dia',
            name='hora',
            field=models.TimeField(default=datetime.time(16, 29, 54, 314520)),
        ),
    ]
